# Generated by Django 3.2.12 on 2023-05-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
