# Generated by Django 3.2.12 on 2023-05-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20230508_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
